### ISSUE TITLE
Add ember-template-lint support

### ISSUE THREAD

**Issue by bryanhickerson** [samuelmeuli/lint-action#40]
I'm interested in adding [ember-template-lint](https://github.com/ember-template-lint/ember-template-lint) as its only our linter that's not currently supported by lint-action. Any objections?

**Comment by samuelmeuli** [comment]
Nope, looks useful 👍

**Comment by elidupuis** [comment]
@bryanhickerson Just came across this issue because I wanted to do the same thing. However, I just realized the ember-template-lint now supports Github annotations by default (as of v1.10.0). It doesn't provide the exact same behaviour as this action; just figured I'd point it out.

https://github.com/ember-template-lint/ember-template-lint/pull/966

**Comment by bryanhickerson** [comment]
Yeah @elidupuis I don't think there's much need add this support anymore.
